name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        submodules: 'true'
    - name: fix ownership
      run: git config --local --add safe.directory '*'
    - name: execute pelican-to-gh action
      uses: rehanhaider/pelican-to-github-pages@v1.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: ${{secrets.DOMAIN_CNAME}}
    #- name: Set ownership
    #  run: chown -R $(id -u):$(id -g) $PWD
